lectures/intro_to_models/apps/author_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^create$', views.create, name='create'),
]

lectures/intro_to_models/apps/first_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^create$', views.create, name='create'),
    url(r'^add_publisher$', views.add_publisher, name = 'add_publisher'),
    url(r'^add_book_to_publisher$', views.add_book_to_publisher, name= 'add_book_to_publisher')
]

lectures/intro_to_models/intro_to_models/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.first_app.urls', namespace='books')),
    url(r'^author/', include('apps.author_app.urls', namespace='authors')),
]

lectures/intro_to_models/apps/author_app/models.py
from __future__ import unicode_literals

from django.db import models
# from ..first_app.models import Book

# Create your models here.
class Author(models.Model):
    name = models.CharField(max_length = 45)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

# one to one relationship
class Description(models.Model):
    content = models.TextField()
    author = models.OneToOneField(Author, related_name = 'authors_desc')
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

# many to many relationship

lectures/intro_to_models/apps/first_app/models.py
from __future__ import unicode_literals

from django.db import models
from ..author_app.models import Author

# Create your models here.

class BookManager(models.Manager):
    def validate_book(self, postData):
        print postData

        errors = []

        if len(postData['title']) < 2:
            errors.append('title is too short')
        # if len(postData['author']) < 2:
        #     errors.append('author is too short')

        response_to_views = {}

        if errors:
            # failed validations
            response_to_views['status'] = False
            response_to_views['errors'] = errors
            # send messge to views
        else:
            # passed validations
            # create the book
            author = Author.objects.get(id=postData['author_id'])
            book = self.create(title = postData['title'], author = author)
            response_to_views['status'] = True
            response_to_views['book'] = book

        return response_to_views

class Book(models.Model):
    author = models.ForeignKey(Author, related_name = 'wrote_by')
    title = models.CharField(max_length = 45)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    objects = BookManager()

class Publisher(models.Model):
    name = models.CharField(max_length = 45)
    books = models.ManyToManyField(Book, related_name = 'published_by')
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

lectures/intro_to_models/apps/author_app/views.py
from django.shortcuts import render, redirect
from .models import Author, Description

# Create your views here.
def create(request):
    if request.method == 'POST':
        # should be done in the models Manager
        author = Author.objects.create(name = request.POST['name'])

        Description.objects.create(content = request.POST['content'], author = author)

    return redirect('books:index')

lectures/intro_to_models/apps/first_app/views.py
from django.shortcuts import render, redirect
from .models import Book, Publisher
from ..author_app.models import Author
from django.contrib import messages

# Create your views here.
def index(request):
    context = {
        'all_books': Book.objects.all(),
        'all_authors': Author.objects.all(),
        'all_publishers': Publisher.objects.all()
    }
    return render(request, 'first_app/index.html', context)


def create(request):
    if request.method == "POST":
        response_from_models = Book.objects.validate_book(request.POST)

        if response_from_models['status']:
            # passed the validations
            # save something in session
            # redirect to a different page
            pass
        else:
            # send a message to the cliend
            for error in response_from_models['errors']:
                messages.error(request, error)

    return redirect('books:index')

def add_publisher(request):
    # should be done inthe manager
    if request.method =='POST':
        Publisher.objects.create(name = request.POST['name'])

    return redirect('books:index')

def add_book_to_publisher(request):
    # should be done inthe manager
    if request.method =='POST':
        book = Book.objects.get(id = request.POST['book_id'])
        publisher = Publisher.objects.get(id = request.POST['publisher_id'])

        publisher.books.add(book)
        
    return redirect('books:index')

lectures/intro_to_models/apps/first_app/templates/first_app/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'first_app/style/index.css' %}">
  </head>
  <body>


    <div class="options">
      <h1>Add Book</h1>
      <form class="" action="{% url 'books:create' %}" method="post">
        {% csrf_token %}
        <p>Title <input type="text" name="title" value=""></p>
        <select class="" name="author_id">
          {% for author in all_authors %}
            <option value="{{ author.id }}">{{ author.name }}</option>
          {% endfor %}
        </select>
        <p><input type="submit" name="" value="Add Book"></p>
      </form>
      <h1>All Books</h1>
      <ul>

        {% for book in all_books %}
          <li>{{ book.title }} written by {{ book.author.name }}</li>
          <ul>
            {% for publisher in book.published_by.all %}
              <li>{{ publisher.name }}</li>
            {% endfor %}
          </ul>
        {% endfor %}
      </ul>
    </div><!-- end_of_options -->



    <div class="options">
      <h1>Add Author</h1>
      <form class="" action="{% url 'authors:create' %}" method="post">
        {% csrf_token %}
        <p>Name <input type="text" name="name" value=""></p>
        <p>Description <input type="text" name="content" value=""></p>
        <p><input type="submit" name="" value="Add author"></p>
      </form>
      <h1>All Authors</h1>
      <ul>
      {% for author in all_authors %}

        <li>{{ author.name }} has a description of {{ author.authors_desc.content }}</li>
          <ul>
            {% for book in author.wrote_by.all %}
              <li>{{ book.title }}</li>
              <ul>
                {% for publisher in book.published_by.all %}
                  <li>{{ publisher.name }}</li>
                {% endfor %}
              </ul>
            {% endfor %}
          </ul>

      {% endfor %}
    </ul>
    </div><!-- end_of_options -->



    <div class="options">
      <h1>Add Publisher</h1>
      <form class="" action="{% url 'books:add_publisher' %}" method="post">
        {% csrf_token %}
        <p><input type="text" name="name" value=""></p>
        <p><input type="submit" name="" value="Add publisher"></p>
      </form>
      <h1>All Publishers</h1>
      {% for publisher in all_publishers %}
        <ul>
          <li>{{ publisher.name }}</li>
          <ul>
            {% for book in publisher.books.all %}
              <li>{{ book.title }} written by {{ book.author.name }} who has a Description of : {{ book.author.authors_desc.content }}</li>
            {% endfor %}
          </ul>
        </ul>
      {% endfor %}
    </div><!-- end_of_options -->



    <div class="options">
      <h1>Add publisher to book</h1>
      <form class="" action="{% url 'books:add_book_to_publisher' %}" method="post">
        {% csrf_token %}
        <p>Book:</p>
        <select class="" name="book_id">
          {% for book in all_books %}
          <option value="{{ book.id }}">{{ book.title }}</option>
          {% endfor %}
        </select>
        <p>Publisher:</p>
        <select class="" name="publisher_id">
          {% for publisher in all_publishers %}
          <option value="{{ publisher.id }}">{{ publisher.name }}</option>
          {% endfor %}
        </select>
        <p><input type="submit" name="" value="Add publisher to book"></p>
      </form>
    </div><!-- end_of_options -->



    {% if messages %}
    {% for message in messages %}
    <p>{{ message }}</p>
    {% endfor %}
    {% endif %}
  </body>
</html>